version: "3"
services:
  go:
    build:
      context: ./go
    ports:
      - 8080:8080
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
