package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"

	"github.com/ogoshikazuki/skill-sheet/graph/model"
)

// BasicInformation is the resolver for the basicInformation field.
func (r *queryResolver) BasicInformation(ctx context.Context) (*model.BasicInformation, error) {
	return &model.BasicInformation{
		Age: 32,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
