// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/ogoshikazuki/skill-sheet/entity"
)

type BasicInformation struct {
	Birthday entity.Date `json:"birthday"`
}

type Query struct {
}
