'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Auth0Provider } from '@auth0/auth0-react'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Auth0Provider
        domain="dev-871m0xngauhlidbd.us.auth0.com"
        clientId="qp5ifGZDBabsDxMZJHzAEMJnmF8saTyz"
        authorizationParams={{
          redirect_uri: "http://localhost:3000"
        }}
      >
        <body className={inter.className}>{children}</body>
      </Auth0Provider>
    </html>
  );
}
