on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "dummy lint for branch protection"
  test:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "dummy test for branch protection"
