on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
      - run: PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f 1.schema.sql
        working-directory: backend/postgres/init
      - run: PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f 2.seed.sql
        working-directory: backend/postgres/init
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'backend/go/go.mod'
          cache-dependency-path: backend/go/go.sum
      - run: cp .env.example .env
        working-directory: frontend/public/nuxt
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v2
        with:
          package_json_file: frontend/public/nuxt/package.json
          run_install: true
      - run: pnpm exec playwright install --with-deps
        working-directory: frontend/public/nuxt
      - run: cd backend/go && PORT=8080 go run . & cd frontend/public/nuxt && pnpm e2e
        env:
          CORS_ALLOWED_ORIGINS: http://localhost:3000
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DBNAME: postgres
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: frontend/public/nuxt/playwright-report/
          retention-days: 30
