on:
  push:
    paths:
      - frontend/public/nuxt/**
defaults:
  run:
    working-directory: ./frontend/public/nuxt
jobs:
  lint:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/actions-setup@v2
      - run: pnpm lint
