on:
  push:
    branches:
      - main
    paths:
      - graphql/**
  pull_request:
    branches:
      - main
    paths:
      - graphql/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v2
        with:
          package_json_file: graphql/package.json
          run_install: true
      - run: pnpm lint
        working-directory: ./graphql
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "dummy test for branch protection"
